services:
  bookeeper:
    build:
      context: .
      dockerfile: Dockerfile
    image: bookeeper:node-lts-alpine
    container_name: bookeeper
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      PORT: "80"
      TZ: Asia/Shanghai
