services:
  bookeeper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookeeper
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Asia/Shanghai
